### ISSUE TITLE
Add sf objects from IVI shapefile data

### ISSUE THREAD

**Issue by wfmackey** [wfmackey/absmapsdata#11]
Kindly sourced and provided by Gaby D'Souza.

**Comment by gabyd** [comment]
👾👾
Thanks Will!

**Comment by wfmackey** [comment]
@gabyd you can use `absmapsdata::regional_ivi2008` to call the regional IVI `sf` object. 

eg:

```
library(tidyverse)
library(sf)
library(absmapsdata)


regional_ivi2008 %>% 
  ggplot() +
  geom_sf(aes(fill = state_name))
```

![image](https://user-images.githubusercontent.com/30094143/63398293-78664580-c410-11e9-9169-cfbb92e84d84.png)

**Comment by gabyd** [comment]
Excellent. Thank you! Just had a play and it works really well. Will fiddle some more! 
Thanks again Will.
