### ISSUE TITLE
Add all ABS correspondences saved as .xlsx files

### ISSUE THREAD

**Issue by gdickens** [wfmackey/absmapsdata#18]
Great package. Thanks for developing it!

Noticed that the get_correspondence_absmaps() function appears to only work where the files are saved as '.xls' in the ABS correspondence file. 

Practically this means that 'object not found' errors are thrown up in these instances eg: 

Correspondences that work (xls in ABS zip file): 
LGA_2011_to_2016 <- get_correspondence_absmaps("LGA", 2011,"LGA", 2016)
LGA_2016_to_2017 <- get_correspondence_absmaps("LGA", 2016,"LGA", 2017)

Correspondences that give me an 'object not found' error (xlsx in ABS zip file)
LGA_2011_to_2018 <- get_correspondence_absmaps("LGA", 2011, "LGA", 2018)
LGA_2014_to_2018 <- get_correspondence_absmaps("LGA", 2014, "LGA", 2018)
LGA_2017_to_2018 <- get_correspondence_absmaps("LGA", 2017, "LGA", 2018)

**Comment by wfmackey** [comment]
Thanks for picking that up @gdickens ! A simple error in my importing function. I'll fix it up sometime today, and make the importing function public.

**Comment by gdickens** [comment]
Welcome. Thanks again for writing it!

**Comment by wfmackey** [comment]
PR #19 updates the package to include all correspondences. Give it a whirl, @gdickens .
