### ISSUE TITLE
Non-ABS geographical structures?

### ISSUE THREAD

**Issue by MattCowgill** [wfmackey/absmapsdata#37]
Would you consider including non-ABS geographical structures, such as Cth Govt 'employment regions'? https://data.gov.au/data/dataset/employment-regions-2015-2020

**Comment by wfmackey** [comment]
Yep will do tonight

**Comment by wfmackey** [comment]
_such as_ doing a lot of work there

**Comment by MattCowgill** [comment]
This is simply one example, Will

**Comment by wfmackey** [comment]
And to actually answer that question: yeah I think non-ABS Australia-focussed geographical structures are welcome in `absmapsdata`. (Despite the package already getting chunky; I might have to look into better ways of doing this).
