### ISSUE TITLE
size of data, and getting on CRAN

### ISSUE THREAD

**Issue by dicook** [wfmackey/absmapsdata#46]
Will, you could follow the style of https://github.com/kevinwang09/learningtower to get the package on CRAN. We elected to provide a small data set in the package, and functions to download the full data from GitHub.

**Comment by wfmackey** [comment]
Thanks @dicook, I think that's a good idea. I recently implemented that approach in the `strayr` package (see here https://github.com/runapp-aus/strayr/blob/master/R/read_absmaps.R), allowing users to download files from the absmapsdata repo, eg: 

```r
strayr::read_absmaps("sa42021")
```

It might be better to keep `absmapsdata` as is (big, heavy and off CRAN), but try to get `strayr` on CRAN. What do you think?

**Comment by dicook** [comment]
I think its good to get strayr on CRAN as a priority, but it doesn't provide maps, right? so there is some benefit of having absmapsdata on CRAN too.

**Comment by wfmackey** [comment]
strayr does (now) provide *access* to maps via the `strayr::read_absmaps` function

**Comment by dicook** [comment]
Oh, that’s all that is needed then!
