### ISSUE TITLE
Aspect ratio observation

### ISSUE THREAD

**Issue by jamesha95** [wfmackey/absmapsdata#5]
It kinda looks like aspect ratios get a little messed up at times (and I'm not sure why); for example, Melbourne looks different in the final map of the README.md.

I think a workaround is to specify the coordinate reference system when you turn off the underlying gridlines with `coord_sf(datum = NA)`. I added the following argument and it seemed to work:

`coord_sf(datum = NA, crs = "+init=epsg:4326")`

According to [this source](https://www.nceas.ucsb.edu/~frazier/RSpatialGuides/OverviewCoordinateReferenceSystems.pdf), an EPSG value of 4326 is what Google Earth uses. 

*For example*
Before, using `coord_sf(datum = NA)`:
![image](https://user-images.githubusercontent.com/42016452/55454311-2ff9e700-562b-11e9-8808-e816d7460a3e.png)

After, using `coord_sf(datum = NA, crs = "+init=epsg:4326")`:
![image](https://user-images.githubusercontent.com/42016452/55454470-c8906700-562b-11e9-941f-20234cae7839.png)

Might be worth noting in the README.md?

**Comment by wfmackey** [comment]
I AGREE JAMES. Can you add a note in the vignette and the README.md file?

**Comment by wfmackey** [comment]
Hey @jamesha95 can you (very very low priority) add a note in a README about this? 

i.e. have a subsection called 'Map projections', maybe after 'Joining with other datasets'(?), where you talk about it for a few lines? I think it would be useful for me/users to understand the command a bit better.
