### ISSUE TITLE
Suburbs shapefiles

### ISSUE THREAD

**Issue by MattCowgill** [wfmackey/absmapsdata#53]
State suburbs (SSC) would be a handy geographical structure to add to `absmapsdata`: https://www.abs.gov.au/ausstats/abs@.nsf/Lookup/by%20Subject/1270.0.55.003~July%202016~Main%20Features~State%20Suburbs%20(SSC)~9

**Comment by wfmackey** [comment]
ABS changed the name from SSC to SAL (suburbs and localities) in 2021. I'm going to add them both and call them both `suburbsYYYY`.

**Comment by MattCowgill** [comment]
CHEERS WILLIAM

**Comment by wfmackey** [comment]
Added both now in #54. Followed the `postcodeYYYY` convention to have filenames `suburb2016` and `suburb2021` (rather than `ssc2016` and `sal2021`). I reckon that clarity is worth it. 

Access with eg `absmapsdata::suburb2021` or `strayr::read_absmap("suburb2021")`
