### ISSUE TITLE
Issue installing absmapdata package

### ISSUE THREAD

**Issue by srssrobin** [wfmackey/absmapsdata#62]
Hey Mac, I am trying to install the absmapdata package directly from your github repo but I keep coming across this error:

Warning message:
In i.p(...) :
  installation of package ‘/tmp/Rtmp6uVlcz/filec786d66f9d4/absmapsdata_1.3.3.tar.gz’ had non-zero exit status

Would you have any suggestions as to how I might be able to install the package? I've used your recommended method (increased timeout to 1000). 

Any advice would be greatly appreciated.

Cheers!

**Comment by wfmackey** [comment]
Hi @srssrobin , apologies for the slow reply. Not sure what the issue is, but best to use the [`strayr`](https://github.com/runapp-aus/strayr) package to pull individual data files from the `absmapsdata` repo
