### ISSUE TITLE
Add Significant Urban Areas (SUA) 2021 and Urban Centres and Localities (UCL) 2021

### ISSUE THREAD

**Issue by tgoddard-tsy** [wfmackey/absmapsdata#68]
[https://www.abs.gov.au/statistics/standards/australian-statistical-geography-standard-asgs-edition-3/jul2021-jun2026/access-and-downloads/digital-boundary-files](https://www.abs.gov.au/statistics/standards/australian-statistical-geography-standard-asgs-edition-3/jul2021-jun2026/access-and-downloads/digital-boundary-files)

**Comment by wfmackey** [comment]
thanks @tgoddard-tsy , this has now been addressed
